### ISSUE TITLE
Wrap current line if no selection is present

### ISSUE THREAD

**Issue by greyvugrin** [Microsoft/vscode-htmltagwrap#8]
This could speed up development by allowing users to skip the highlighting portion if they know they want to wrap all text in the line where the cursor is located

**Comment by j0xhn** [comment]
+1

**Comment by bgashler1** [comment]
This issue was moved to bgashler1/vscode-htmltagwrap#6

**Comment by greyvugrin** [comment]
No sense in keeping in open then! Thanks
